spring:
  datasource:
    url: jdbc:h2:file:./service_monitor_data/monitor;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
