create table service_health_events (
    id bigint generated by default as identity primary key,
    target varchar(64) not null,
    status varchar(16) not null,
    detail varchar(500) not null,
    checked_at timestamp not null
);

create index idx_service_health_events_target_checked_at
    on service_health_events(target, checked_at);

create table incidents (
    id bigint generated by default as identity primary key,
    target varchar(64) not null,
    status varchar(16) not null,
    started_at timestamp not null,
    resolved_at timestamp,
    start_detail varchar(500) not null,
    resolution_detail varchar(500)
);

create index idx_incidents_target_started_at
    on incidents(target, started_at);

create index idx_incidents_status
    on incidents(status);
